WIP: Quick search e2e
vmware/vmware-cloud-director-ui-components pull request #329
Opened 2021-04-01 17:13 UTC by RiaMahoney

Work in Progress - Changes paired with [this GitLab MR](https://gitlab.eng.vmware.com/core-build/vcd_ui/-/merge_requests/3584)

Quick Search widget object for E2E tests, following new WO pattern.

2021-04-01 20:15 UTC, ryan-bradford approved these changes
Can we make a followup ticket to convert the quick search unit tests to use this new widget? With this merge, we're going to have two quick search widgets and that's not idea.

Also, approved pending any review changes in GitLab

2021-04-01 20:15 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.component.html
> +        <li
This has been changed to a single no results section. Just something to be aware of when you rebase.

2021-04-01 20:15 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.wo.ts
> +export class QuickSearchWo<T> extends BaseWidgetObject<T> {
NIT: add a comment to this class

2021-04-02 22:57 UTC, juanmendes commented on projects/components/src/quick-search/quick-search.component.html
> +                data-ui="section-title"
Why isn't this using `DataUi.sectionTitle`?

2021-04-02 22:57 UTC, juanmendes commented on projects/components/src/quick-search/quick-search.component.html
> +    <div class="modal-body" [attr.data-ui]="DataUi.quickSearchModal">
There's no need to prefix the name with quickSearch since it's already contextual to quick search. `modal-body` seems more concise and descriptive

2021-04-02 22:57 UTC, juanmendes commented on projects/components/src/quick-search/quick-search.dataui.ts
> +export const QuickSearchDataUi = {
Why the long name instead of just DataUi?

2021-04-20 18:14 UTC, ryan-bradford requested changes

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.wo.ts
> +     * Search results are loading if the spinner exists, that is, if it has length > 0.
This comment does not describe anything about the method `getSpinner`. It describes something about TestElement (how .length works). Rework this comment to describe on a higher-level what this getter gets.

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.wo.ts
> +     * Accesses the page object behind the Quick Search modal
"Returns the element behind the Quick Search modal" I think is a little more clear

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.wo.ts
> +     * Returns the alerts to the user about their search input, if necessary
Don't need "if necessary"

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.wo.ts
> +     * Returns the element (invisible to the user) that represents the top of the search results
These elements are not invisible to the user. They display on the top and on the bottom of quick search.

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.wo.ts
> +     * Returns the element (invisible to the user) that represents the bottom of the search results
Same as above

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts
> +     * Gives the value of the placeholder text in the search input box
This is generic for all elements, so this isn't necessarily a "search input".  Reword this comment to be more general

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts
> +    type(value: string): void {
Add a comment to this method

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.component.spec.ts
> +@Component({
NIT: move this back to the bottom of the file so it doesn't show in the diff

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.component.spec.ts
> +interface HasAngularFinder {
Is this used?

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.component.spec.ts
> +            expect(this.quickSearch.getSpinner().length()).not.toBe(
NIT: can we change this to `expect(this.quickSearch.getSpinner().length()).toBe(1, ...)` or whatever the correct number is. Just find it easier to read

2021-04-20 18:14 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.component.spec.ts
> +            it('is not called when pressing enter and there is no selection', function (this: Test): void {
Something weird going on with the diff here... let's see if we can make this go away

2021-04-21 20:33 UTC, ryan-bradford commented on projects/components/src/quick-search/quick-search.component.spec.ts
>          });
Add }); back in

2021-04-21 20:33 UTC, ryan-bradford approved these changes

2021-04-21 21:21 UTC, merged